version: 1
services:
  - type: web
    name: youtube-music-download-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    branches:
      - main
    deploy:
      branch: main
